const FETCH_FILM_STARTED = 'FETCH_FILMS_STARTED';
const FETCH_FILM_SUCCEEDED = 'FETCH_FILMS_SUCCEEDED';
const FETCH_FILM_FAILED = 'FETCH_FILM_FAILED';

export { FETCH_FILM_STARTED, FETCH_FILM_SUCCEEDED, FETCH_FILM_FAILED };
